// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8op4wtW7g29lbUhSMAnS-gEVjYElDMU',
    appId: '1:531965731071:web:c8f8efae2ea6b619856cca',
    messagingSenderId: '531965731071',
    projectId: 'main-proj-app',
    authDomain: 'main-proj-app.firebaseapp.com',
    storageBucket: 'main-proj-app.appspot.com',
    measurementId: 'G-DHL3KCDHC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_RA49a7FX-nTIAeXtDmurCsfvvc6kUK0',
    appId: '1:531965731071:android:f865ad6d65eda654856cca',
    messagingSenderId: '531965731071',
    projectId: 'main-proj-app',
    storageBucket: 'main-proj-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbIvEF1OHtCIfb8LEpCSesmKWr8RMEaPE',
    appId: '1:531965731071:ios:9d8c5b603446cd7c856cca',
    messagingSenderId: '531965731071',
    projectId: 'main-proj-app',
    storageBucket: 'main-proj-app.appspot.com',
    iosBundleId: 'com.example.mainSociavism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbIvEF1OHtCIfb8LEpCSesmKWr8RMEaPE',
    appId: '1:531965731071:ios:fc37b953d18fd9f5856cca',
    messagingSenderId: '531965731071',
    projectId: 'main-proj-app',
    storageBucket: 'main-proj-app.appspot.com',
    iosBundleId: 'com.example.mainSociavism.RunnerTests',
  );
}
